server:
  port: 8080

spring:
  datasource:
    username: test
    password: test
    url: jdbc:mysql://localhost/suntv?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    cache-second: 1
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20 # 最大空闲连接数
    min-idle: 0 # 最小空闲连接数
    timeout: 3000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: net.ruixinglong.suntv.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    net.ruixinglong.suntv.mapper: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true

authorization:
  secret: test1

aliyun:
  accessKeyId: LTAI4FrKXRqfyakYFdXbEc7M
  secret: nAXjlAjShJ7cdhrOoBV4deQAXJvqjT
  sms:
    SignName: SunTV
    TemplateCode: SMS_175570808

pagination:
  pageSize: 1